name: Entity-Normalization-Engine
channels:
  - pytorch
  - huggingface
  - defaults
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - click=8.0.1
  - cryptography=3.4.7
  - cudatoolkit=10.2.89
  - dataclasses=0.8
  - filelock=3.0.12
  - freetype=2.10.4
  - huggingface_hub=0.0.13
  - idna=2.10
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.2.0
  - joblib=1.0.1
  - jpeg=9b
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - lz4-c=1.9.3
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - ninja=1.10.2
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pillow=8.2.0
  - pip=21.1.3
  - protobuf=3.14.0
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.8.10
  - python_abi=3.8
  - pytorch=1.9.0
  - pyyaml=5.4.1
  - regex=2021.4.4
  - requests=2.25.1
  - sacremoses=master
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - tokenizers=0.10.3
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - tqdm=4.61.1
  - transformers=4.8.1
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - urllib3=1.26.6
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - huggingface-hub==0.0.12
    - nltk==3.6.2
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - sentence-transformers==2.0.0
    - sentencepiece==0.1.96
    - threadpoolctl==2.1.0
